global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'uaszgpt-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'uaszgpt-ia'
    static_configs:
      - targets: ['ia-engine:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']